version: "3.9"

services:
  app:
    build:
      context: /home/sufiyan/nest-app
    container_name: nest-app
    env_file:
      - .env
    environment:
      # Override or ensure MONGO_URI is set for container-to-container networking
      - MONGO_URI=mongodb://mongo:27017/nest
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local


